export type Command = { name: string; description: string; category: string };
export const commands: Command[] = [
  ["ticket", "Tickets privés avec transcripts HTML", "Support"],
  ["salon", "Créer et gérer les salons", "Administration"],
  ["categorie", "Gérer les catégories", "Administration"],
  ["vocal-temp", "Vocaux temporaires", "Administration"],
  ["moderation", "Ban, unban, kick, timeout, avertissements, nuke et purge de liens", "Modération"],
  ["automod", "Protection automatique du serveur", "Modération"],
  ["bienvenue", "Messages de bienvenue personnalisés", "Communauté"],
  ["aurevoir", "Messages de départ", "Communauté"],
  ["autorole", "Rôles automatiques", "Communauté"],
  ["niveaux", "Configuration et gestion de l'XP", "Niveaux"],
  ["rank", "Voir un niveau", "Niveaux"],
  ["leaderboard", "Classement XP", "Niveaux"],
  ["logs", "Journaux du serveur", "Administration"],
  ["stream", "Annoncer un live", "Streaming"],
  ["twitch", "Alertes Twitch Helix", "Streaming"],
  ["live-role", "Rôle automatique des streamers", "Streaming"],
  ["stream-planning", "Planning hebdomadaire", "Streaming"],
  ["communaute", "Sondages, suggestions et giveaways", "Communauté"],
  ["embed", "Créer un embed", "Utilitaires"],
  ["reaction-role", "Menus de rôles", "Communauté"],
  ["rappel", "Programmer un rappel", "Utilitaires"],
  ["info", "Avatar, utilisateur, serveur et aide", "Utilitaires"],
  ["economie", "Daily, solde et travail", "Économie"],
  ["antiraid", "Protection anti-raid", "Sécurité"],
  ["lockdown", "Verrouillage général", "Sécurité"],
  ["invitation", "Créer et suivre les invitations", "Administration"],
  ["role", "Créer et attribuer des rôles et mots-clés", "Administration"],
  ["setup", "Installer la structure complète", "Administration"],
  ["membres", "Lister, chercher et compter les membres", "Administration"],
  ["mr-robot", "Infos, statut, configuration, jeux et annonces", "Utilitaires"],
].map(([name, description, category]) => ({ name, description, category }));
